--CREATE TABLE presta_savings.t_customer (
--    member_number VARCHAR(25) PRIMARY KEY,
--    mobile VARCHAR(25),
--    government_id INT,
--    profile_image_id VARCHAR(255),
--    user_id INT,
--    FOREIGN KEY (user_id) REFERENCES t_user(user_id)
--);