version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: savingsDB-container
    environment:
      MYSQL_ROOT_PASSWORD: pass@123
      MYSQL_DATABASE: savings
      MYSQL_USER: root
      MYSQL_PASSWORD: pass@123
    ports:
      - "3306:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
