version: '3.8'

services:
#  app:
#    build: .
#    ports:
#      - "8081:8090"
#    depends_on:
#      - mysql
#    networks:
#      - ps-network

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: presta-savings
      MYSQL_USER: root

    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - ps-network

networks:
  ps-network:
    driver: bridge