spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/presta_savings
    username: postgres
    password: pass@123
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop