server:
  servlet:
   context-path: /savings
  error:
    include-message: always

spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/presta_savings
    username: root
    password: pass@123
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always