server:
  port: 8088

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/presta_savings
    username: root
    password: pass@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

sms:
  gateway:
    endpoint: https://api2.tiaraconnect.io/api/messaging/sendsms
    apikey: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzMzgiLCJvaWQiOjMzOCwidWlkIjoiNTQ4ZmRlYzUtMzJhNy00MDc4LTk4ZGItOTVlNjI3YTcxOWUwIiwiYXBpZCI6NDE3LCJpYXQiOjE3MzM3Mzg3OTQsImV4cCI6MjA3MzczODc5NH0.g_Qwr8jyYe-Lml3gjrgM94Y2rxDN9hpPg_gf75iGOIXJbYvgbpBWfEw_JBWrOq8lnIW1DZf5qFTFzB3xBgSMXQ
