package dev.marvin.savings.auth;

public enum Permission {
    CUSTOMER_CREATE,
    CUSTOMER_READ,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    ACCOUNT_CREATE,
    ACCOUNT_READ,
    ACCOUNT_UPDATE,
    ACCOUNT_DELETE,
    TRANSACTION_CREATE,
    TRANSACTION_READ
}
